### ISSUE TITLE
Component should not inject script tags

### ISSUE THREAD

**Issue by warrenclearmetal** [announcekitapp/announcekit-react#8]
When we attempted to integrate this into our project, it broke tests due to the script tag that is being injected.

Having a component directly mutate the DOM in this way is not how React is intended to be used.

The external script that is needed should be provided as part of a template HTML file rather than directly injected by the component itself.

Unfortunately, I don't see a backward-compatible way to make this change.

**Comment by eknkc** [comment]
The external script is required to load the widget and it is part of the Announcekit deploy process so that script is being updated all the time due to new features / bugfixes etc. It would be impossible to reflect the script updates here and that's why we load the dynamic script. What would be your exact requirement for this to work on your setup?

**Comment by dacevedo12** [comment]
```
TypeError: Cannot read property 'parentNode' of undefined

AnnounceKit.Object.<anonymous>.AnnounceKit.componentDidMount (node_modules/announcekit-react/dist/index.js:69:17)
```
Consider making it resilient if the script tag wasn't created for some reason as the jest runner does not have DOM by default.
Or even better, documenting use with testing suites (mocking it so it doesn't fail or adding JSDOM)

Thanks
